### ISSUE TITLE
问问

### ISSUE THREAD

**Issue by HsiangNianian** [imldy/QQFileForward#1]
怎么用a，指令是啥

**Comment by imldy** [comment]
放到插件目录，改好配置文件，然后启动console就能用，目前不需要指令。

**Comment by HsiangNianian** [comment]
> 放到插件目录，改好配置文件，然后启动console就能用，目前不需要指令。

改好配置文件？目录在哪里呀，我在config里面只找到一个空文件夹

**Comment by imldy** [comment]
你好，README已更新使用教程。
